#!/bin/bash
#
# If you are reading this, you have wandered out of bounds and are reading 
# the code that drives the game. CONGRATULATIONS!
#
# Learning Linux is all about curiosity, so read what you can of this code 
# and see if you can figure out what it does.
#
# Or just continue playing the game. Make sure to read the scrolls. If you're 
# stuck, go to the repo (google classroom) and ask. We're happy to help!

clear
cat << EOF

    The beige computer terminal in the lobby has come alive! Now the 
    display is glowing a fuzzy CRT green. You tap the keyboard and 
    are met with the following prompt:  


            ===============================================
            #         PHYSICAL SECURITY INTERFACE         #
            #                                             #
            #         Insert Access Card to Begin:        #
            ===============================================

            [ sentinel@bsd ~ ] > 



    You MAY have run across some information that could
    work here....

EOF

    printf "Do you have an access-card in your bag?  Y/n:  "
    read RESP

    if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then
        if grep  --quiet --only-matching 'access-card' <<< ${BAG}; then
            clear
            cat << EOF


            ===============================================
            #         PHYSICAL SECURITY INTERFACE         #
            #                                             #
            #         Insert Access Card to Begin:        #
            ===============================================


             >    ###  A C C E S S   G R A N T E D  ###



EOF
sleep 3
mv ./.d-wing ./d-wing
cat << EOF
    The terminal emits a long beep -- ACCESS GRANTED flashes and 
    the door to D-Wing opens. The adventure continues... 
EOF