#!/bin/bash
#
# If you are reading this, you have wandered out of bounds and are reading 
# the code that drives the game. CONGRATULATIONS!
#
# Learning Linux is all about curiosity, so read what you can of this code 
# and see if you can figure out what it does.
#
# Or just continue playing the game. Make sure to read the scrolls. If you're 
# stuck, go to the repo (google classroom) and ask. We're happy to help!

clear
cat << EOF

    As you turn around, an object catches your eye. 
    Upon the southern wall, there is elaborate oak 
    paneling. You notice a handle about waist high. 

    You move forward to take a closer look and see 
    that if you pull it up, it could expose a 
    hidden panel.


EOF
printf "Have you explored the LIBRARY yet? Do you want to turn the\nknob and open ?  Y/n:  "
read RESP

if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then
    clear
    cat << EOF

    You recall hearing the same whirring fan noise at the school entrance. 
    Pulling the handle UP reveals another vintage computer terminal. 

    Unable to hold back your curiosity, you move up to the terminal and 
    tap the SPACEBAR. The display glows, displaying the following:


            # In Bash, a symbolic link (symlink) is a 
            # *shortcut* to another file or directory. 
            # Create one from: HERE  ==to==>  ENTRANCE


          ln -fs ../../../../../entrance/ panel-door


            # Then, pass through the panel-door with `cd`

EOF
else
    clear
    cat << EOF

You decide it is probably best to leave these kind of things alone. Who 
knows, they could be a booby trap.


EOF

fi



























































































































































































































































































































# Hmm, that didn't work.
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./handle

