#!/bin/bash
#
# If you are reading this, you have wandered out of bounds and are reading 
# the code that drives the game. CONGRATULATIONS!
#
# Learning Linux is all about curiosity, so read what you can of this code 
# and see if you can figure out what it does.
#
# Or just continue playing the game. Make sure to read the scrolls. If you're 
# stuck, go to the repo (google classroom) and ask. We're happy to help!


if ! grep  --quiet --only-matching coin <<< $BAG; then

clear
cat << EOF


                             _.-'~~`~~'-._
                          .  B   E   R   `  .
                         / I               T  \
                       /`        -'~"-.        \
                      ; L      / `-    \      Y ;
                     ;        />  `.  -.|        ;
                     |       /_     '-.__)       |
                     |        |-  _.' \ |        |
                     ;        `~~;     \\        ;
                      ; IN GOD WE /      \\)    ;
                       \  TRUST '.___.-'`"     /
                        \                   /`
                          '._   2 0 2 2   _.'
                             `'-..,,,..-'`

        You have found a minty new **Quarter**! Money is always
        good to have around, right?

        Do you want to pick it up?  Y/n: 


EOF
read RESP

if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then
    clear
    cat << EOF

        The money is yours now! Prefix this item to 
        your inventory:


            export BAG=coin,\$BAG


-----------------------------------------------------------------------
TIP:
- Remember, you can always check your inventory by running:
    - echo \$BAG


EOF
fi

else
    clear
    echo "This treasure has already been taken."
    echo ""
    echo ""

fi

# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 

# Hmm, that didn't work.
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./treasure