#!/bin/bash
#
# If you are reading this, you have wandered out of bounds and are reading 
# the code that drives the game. CONGRATULATIONS!
#
# Learning Linux is all about curiosity, so read what you can of this code 
# and see if you can figure out what it does.
#
# Or just continue playing the game. Make sure to read the scrolls. If you're 
# stuck, go to the repo (google classroom) and ask. We're happy to help!


echo
if ! grep  --quiet --only-matching 'access-card' <<< $BAG; then
    clear
    cat << EOF



                                ______________________________________
                               |                                      |
                    _.---------|.--.                                  |
                 .-'          ./    \                                 |
              .-'           .' |    /|                                |
           .-'         |   /   '.__//                                 |
        .-'           _.--/        /                                  |
       |        _  .-'   /        /                                   |
       |     ._  \      /     \`  /                                   |
       |        ' .    /     \`  /____________________________________|
       |         \ \ '/        /
       |        - \  /        /|
       |        '  .'        / |
       |          '         |.'|
       |                    |  |
       |                    |  |
       |                    |.'
       |                    /
       |                   /
       |                  /
       )                 /


        You have found a **Access Card** on a lanyard! This thing seems 
        like it will really come in handy! A light emanates from your 
        eyes as you think you MAY begin to remember this place...

        Add this item to your inventory by running:


            export BAG=access-card,\$BAG


        Remember, you can check your inventory:


            echo \$BAG


EOF

mv ../../../.terminal ../../../terminal 2>/dev/null
rm ../../../computer 2>/dev/null

else
    echo "      This item has already been taken."
    echo ""
    echo ""
fi








































































































































































































































































































































# Hmm, that didn't work.
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./treasure

