#!/bin/bash
#
# If you are reading this, you have wandered out of bounds and are reading 
# the code that drives the game. CONGRATULATIONS!
#
# Learning Linux is all about curiosity, so read what you can of this code 
# and see if you can figure out what it does.
#
# Or just continue playing the game. Make sure to read the scrolls. If you're 
# stuck, go to the repo (google classroom) and ask. We're happy to help!

machine() {
            |############################################|
            |#|                           |##############|
            |#|  =====  ..--''`  |~~``|   |##|````````|##|
            |#|  |   |  \     |  :    |   |##| Exact  |##|
            |#|  |___|   /___ |  | ___|   |##| Change |##|
            |#|  /=__\  ./.__\   |/,__\   |##| Only   |##|
            |#|  \__//   \__//    \__//   |##|________|##|
            |#|===========================|##############|
            |#|```````````````````````````|##############|
            |#| =.._      +++     //////  |##############|
            |#| \/  \     | |     \    \  |#|`````````|##|
            |#|  \___\    |_|     /___ /  |#| _______ |##|
            |#|  / __\\  /|_|\   // __\   |#| |1|2|3| |##|
            |#|  \__//-  \|_//   -\__//   |#| |4|5|6| |##|
            |#|===========================|#| |7|8|9| |##|
            |#|```````````````````````````|#| ``````` |##|
            |#| ..--    ______   .--._.   |#|[=======]|##|
            |#| \   \   |    |   |    |   |#|  _   _  |##|
            |#|  \___\  : ___:   | ___|   |#| ||| ( ) |##|
            |#|  / __\  |/ __\   // __\   |#| |||  `  |##|
            |#|  \__//   \__//  /_\__//   |#|  ~      |##|
            |#|===========================|#|_________|##|
            |#|```````````````````````````|##############|
            |############################################|
            |#|||||||||||||||||||||||||||||####```````###|
            |#||||||||||||PUSH|||||||||||||####\|||||/###|
            |############################################|
            \\\\\\\\\\\\\\\\\\\\\\///////////////////////
            |_________________________________________|
}





clear
cat << EOF

            You see a hulking vending machine here and
            notice all the deliciously sweet treats in
            there       "mmmmmmmmmMMMMMMM"


EOF
machine
echo ""
echo ""

read -rp "        Do you have a quarter on you?  Y/n: " RESP


# don't have one
no_coin () {
    clear
    cat << EOF


        You sense that the vending machine requires something
        monetary in nature. Whatever that is, you cannot provide
        it now. Walk with care.


EOF
}

# have a coin in bag
if [ "$RESP" = "y" ] || [ "$RESP" = "Y" ]; then
    if grep  --quiet --only-matching coin <<< $BAG; then
        clear
        cat << EOF


        You place the quarter in the machine and make your selection.
        You pound a small bag of Sour Patch Kids, and feel the power 
        of 1000mg of sugar coursing through you.


EOF
        touch .sugar-rush
    else
        no_coin
    fi
else
    no_coin
fi


















































































































































































































































































# Hmm, that didn't work.

# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./glass


