#!/bin/bash
#
# If you are reading this, you have wandered out of bounds and are reading 
# the code that drives the game. CONGRATULATIONS!
#
# Learning Linux is all about curiosity, so read what you can of this code 
# and see if you can figure out what it does.
#
# Or just continue playing the game. Make sure to read the scrolls. If you're 
# stuck, go to the repo (google classroom) and ask. We're happy to help!


damage() {
    clear
    cat << EOF

        You try to resist, but you cannot.  You dip open mouth
        into the "bubbler" and feel immediate discomfort.

        "This... this is... SUGAR and CAFFEINE FREE SODA! 
        BLEGGHH!!!"

        The pain snaps you out of your dazed state, and only
        suffer -2 HP. Remember to deduct 2 points from your
        HP variable:

            let "HP=HP-2"


EOF

}

DAMAGE=`find .. -type f -name ".damage"`

printf "        Do you want to approach the fountain?  Y/n:  "
read RESP

if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then
    cat << EOF

        The fountain sparkles in the intensity of your 
        thirst. You feel drawn to it.


EOF
    if [ x$DAMAGE = "x" ]; then
        cat << EOF

        But you suddenly feel strength to turn away. You hear a shriek 
        from a nearby classroom A-Wing!


EOF
   else
       damage
   fi
else
    if [ ! -z "$DAMAGE" ]; then
	damage
    fi
fi

[ -f ../.damage ] && rm ../.damage
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Well that didn't work!
